-- MySQL Script generated by MySQL Workbench
-- Mon Mar 27 20:13:13 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema weingutmerlot
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema weingutmerlot
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `weingutmerlot` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `weingutmerlot` ;

-- -----------------------------------------------------
-- Table `weingutmerlot`.`agragebiete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weingutmerlot`.`agragebiete` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `size` INT NOT NULL COMMENT 'In hectar',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weingutmerlot`.`agragebietsektionen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weingutmerlot`.`agragebietsektionen` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `agragebiet_id` INT NOT NULL,
  `weinrebe_id` INT NOT NULL,
  `size` INT NOT NULL COMMENT 'In hectar',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_agragebietsektionen_agragebiet1`
    FOREIGN KEY (`agragebiet_id`)
    REFERENCES `weingutmerlot`.`agragebiete` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agragebietsektionen_weinrebe1`
    FOREIGN KEY (`weinrebe_id`)
    REFERENCES `weingutmerlot`.`weinreben` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_agragebietsektionen_agragebiet1_idx` ON `weingutmerlot`.`agragebietsektionen` (`agragebiet_id` ASC) VISIBLE;

CREATE INDEX `fk_agragebietsektionen_weinrebe1_idx` ON `weingutmerlot`.`agragebietsektionen` (`weinrebe_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `weingutmerlot`.`chargen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weingutmerlot`.`chargen` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `weintyp_id` INT NOT NULL,
  `jahrgang` INT NOT NULL DEFAULT year(curdate());,
  `lagerungsort` VARCHAR(255) NULL,
  `menge_in_liter` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_wein_weintyp1`
    FOREIGN KEY (`weintyp_id`)
    REFERENCES `weingutmerlot`.`weine` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_wein_weintyp1_idx` ON `weingutmerlot`.`chargen` (`weintyp_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `weingutmerlot`.`gärungsprozesse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weingutmerlot`.`gärungsprozesse` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `weine_id` INT NOT NULL,
  `zuckergehalt` INT NOT NULL,
  `temperatur` INT NOT NULL,
  `dauer` INT NULL COMMENT 'Berechnet',
  `lagerungsbehaelter` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_gärungsprozesse_weine1`
    FOREIGN KEY (`weine_id`)
    REFERENCES `weingutmerlot`.`weine` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_gärungsprozesse_weine1_idx` ON `weingutmerlot`.`gärungsprozesse` (`weine_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `weingutmerlot`.`gärungsprozessschritte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weingutmerlot`.`gärungsprozessschritte` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `gärungsprozess_id` INT NOT NULL,
  `nach_zeit` INT NOT NULL,
  `soll_zucker` INT NOT NULL,
  `soll_temperatur` INT NOT NULL,
  `soll_alkohol` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_gärungsprozessschritte_gärungsprozess1`
    FOREIGN KEY (`gärungsprozess_id`)
    REFERENCES `weingutmerlot`.`gärungsprozesse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_gärungsprozessschritte_gärungsprozess1_idx` ON `weingutmerlot`.`gärungsprozessschritte` (`gärungsprozess_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `weingutmerlot`.`gärungsprozessschritte_has_hefen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weingutmerlot`.`gärungsprozessschritte_has_hefen` (
  `gärungsprozessschritte_id` INT NOT NULL,
  `hefen_id` INT NOT NULL,
  `menge` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`gärungsprozessschritte_id`, `hefen_id`),
  CONSTRAINT `fk_gärungsprozessschritte_has_hefen_gärungsprozessschritte1`
    FOREIGN KEY (`gärungsprozessschritte_id`)
    REFERENCES `weingutmerlot`.`gärungsprozessschritte` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gärungsprozessschritte_has_hefen_hefen1`
    FOREIGN KEY (`hefen_id`)
    REFERENCES `weingutmerlot`.`hefen` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_gärungsprozessschritte_has_hefen_hefen1_idx` ON `weingutmerlot`.`gärungsprozessschritte_has_hefen` (`hefen_id` ASC) VISIBLE;

CREATE INDEX `fk_gärungsprozessschritte_has_hefen_gärungsprozessschritt_idx` ON `weingutmerlot`.`gärungsprozessschritte_has_hefen` (`gärungsprozessschritte_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `weingutmerlot`.`hefen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weingutmerlot`.`hefen` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `art` VARCHAR(255) NOT NULL,
  `temperatur` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weingutmerlot`.`überprüfungen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weingutmerlot`.`überprüfungen` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `chargen_id` INT NOT NULL,
  `gärungsprozessschritte_id` INT NOT NULL,
  `ist_zucker` INT NOT NULL,
  `ist_temperatur` INT NOT NULL,
  `ist_alkohol` INT NOT NULL,
  `anpassung_zucker` INT NOT NULL,
  `anpassung_temperatur` INT NOT NULL,
  `nächster_schritt` TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'BOOLEAN',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_überprüfungen_chargen1`
    FOREIGN KEY (`chargen_id`)
    REFERENCES `weingutmerlot`.`chargen` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_überprüfungen_gärungsprozessschritte1`
    FOREIGN KEY (`gärungsprozessschritte_id`)
    REFERENCES `weingutmerlot`.`gärungsprozessschritte` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_überprüfungen_chargen1_idx` ON `weingutmerlot`.`überprüfungen` (`chargen_id` ASC) VISIBLE;

CREATE INDEX `fk_überprüfungen_gärungsprozessschritte1_idx` ON `weingutmerlot`.`überprüfungen` (`gärungsprozessschritte_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `weingutmerlot`.`überprüfungen_has_hefen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weingutmerlot`.`überprüfungen_has_hefen` (
  `überprüfungen_id` INT NOT NULL,
  `hefen_id` INT NOT NULL,
  `ist` INT NOT NULL,
  `anpassung` INT NOT NULL,
  PRIMARY KEY (`überprüfungen_id`, `hefen_id`),
  CONSTRAINT `fk_überprüfungen_has_hefen_überprüfungen1`
    FOREIGN KEY (`überprüfungen_id`)
    REFERENCES `weingutmerlot`.`überprüfungen` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_überprüfungen_has_hefen_hefen1`
    FOREIGN KEY (`hefen_id`)
    REFERENCES `weingutmerlot`.`hefen` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_überprüfungen_has_hefen_hefen1_idx` ON `weingutmerlot`.`überprüfungen_has_hefen` (`hefen_id` ASC) VISIBLE;

CREATE INDEX `fk_überprüfungen_has_hefen_überprüfungen1_idx` ON `weingutmerlot`.`überprüfungen_has_hefen` (`überprüfungen_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `weingutmerlot`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weingutmerlot`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(255) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `weingutmerlot`.`weinarten`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weingutmerlot`.`weinarten` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `art` ENUM("Rotwein", "Weißwein", "Roséwein", "Schaumwein", "Perlwein", "Dessertwein", "Likörwein") NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weingutmerlot`.`weinarten_has_weinreben`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weingutmerlot`.`weinarten_has_weinreben` (
  `weinarten_id` INT NOT NULL,
  `weinreben_id` INT NOT NULL,
  `menge` DECIMAL(13,10) NOT NULL COMMENT 'Menge In Prozent von Chargengröße',
  PRIMARY KEY (`weinarten_id`, `weinreben_id`),
  CONSTRAINT `fk_weinarten_has_weinreben_weinarten1`
    FOREIGN KEY (`weinarten_id`)
    REFERENCES `weingutmerlot`.`weinarten` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_weinarten_has_weinreben_weinreben1`
    FOREIGN KEY (`weinreben_id`)
    REFERENCES `weingutmerlot`.`weinreben` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_weinarten_has_weinreben_weinreben1_idx` ON `weingutmerlot`.`weinarten_has_weinreben` (`weinreben_id` ASC) VISIBLE;

CREATE INDEX `fk_weinarten_has_weinreben_weinarten1_idx` ON `weingutmerlot`.`weinarten_has_weinreben` (`weinarten_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `weingutmerlot`.`weine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weingutmerlot`.`weine` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `weinart_id` INT NOT NULL,
  `suessegrad` ENUM("Trocken", "Halbtrocken", "Lieblich", "Süß", "Feinherb") NOT NULL COMMENT 'ENUM(Trocken, Halbtrocken, Lieblich, Süß, Feinherb)',
  `alkoholgehalt` INT NOT NULL,
  `beschreibung` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_weine_weinart1`
    FOREIGN KEY (`weinart_id`)
    REFERENCES `weingutmerlot`.`weinarten` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_weine_weinart1_idx` ON `weingutmerlot`.`weine` (`weinart_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `weingutmerlot`.`wein_has_Zutaten`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weingutmerlot`.`wein_has_Zutaten` (
  `wein_id` INT NOT NULL,
  `Zutaten_id` INT NOT NULL,
  `menge` INT NOT NULL DEFAULT 0 COMMENT 'Menge In Prozent von Chargengröße',
  `menge_einheit` VARCHAR(10) NOT NULL DEFAULT 'g' COMMENT 'Wird immer auf einen Liter gerechnet',
  PRIMARY KEY (`wein_id`, `Zutaten_id`),
  CONSTRAINT `fk_wein_has_Zutaten_wein1`
    FOREIGN KEY (`wein_id`)
    REFERENCES `weingutmerlot`.`weine` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wein_has_Zutaten_Zutaten1`
    FOREIGN KEY (`Zutaten_id`)
    REFERENCES `weingutmerlot`.`zutaten` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_wein_has_Zutaten_Zutaten1_idx` ON `weingutmerlot`.`wein_has_Zutaten` (`Zutaten_id` ASC) VISIBLE;

CREATE INDEX `fk_wein_has_Zutaten_wein1_idx` ON `weingutmerlot`.`wein_has_Zutaten` (`wein_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `weingutmerlot`.`weinreben`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weingutmerlot`.`weinreben` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weingutmerlot`.`zutaten`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weingutmerlot`.`zutaten` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE USER 'weingut_merlot' IDENTIFIED BY 'weingut_merlot';

GRANT ALL ON `weingutmerlot`.* TO 'weingut_merlot';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
